---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maec-scsp-pre

resources:
  - ../../base

patches:
  - path: patch-pre.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: scsp-frontend
