---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scsp-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: jws-tomcat
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2"
