---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scsp-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: jws-tomcat
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
