---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scsp-frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: jws-tomcat
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
