infinispan.client.hotrod.server_list=scsp-session-cache.maec-scsp-s2i.svc.cluster.local:11222
infinispan.client.hotrod.marshaller=org.infinispan.commons.marshall.JavaSerializationMarshaller
infinispan.client.hotrod.client_intelligence=BASIC
infinispan.client.hotrod.socket_timeout=5000
infinispan.client.hotrod.connect_timeout=3000
