name: "CI Validation: Lints & Architecture Manifests"

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: "Lint & Validate Manifests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kustomize
        run: |
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz" | tar -xz -C /tmp
          sudo mv /tmp/kustomize /usr/local/bin/
          kustomize version

      - name: Set up yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint -c .yamllint.yml .

      - name: Validate Solution A Kustomize Base
        run: kustomize build solution-a-gitops/kustomize/base > /dev/null

      - name: Validate Solution A Kustomize QA Overlay
        run: kustomize build solution-a-gitops/kustomize/overlays/qa > /dev/null

      - name: Validate Solution A Kustomize PRE Overlay
        run: kustomize build solution-a-gitops/kustomize/overlays/pre > /dev/null

      - name: Validate Solution A Kustomize PRO Overlay
        run: kustomize build solution-a-gitops/kustomize/overlays/prod > /dev/null

      - name: Validate Bash Scripts Syntax
        run: |
          echo "Checking shell scripts syntax..."
          find . -name "*.sh" -exec bash -n {} +
          echo "All shell scripts passed syntax check!"
